language: node_js
node_js:
  - "4.2.1"

branches:
  only:
    - master
    - dev

# Install GCC-4.8: https://github.com/bnoordhuis/node-iconv/issues/132
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
sudo: false
env:
  - CXX=g++-4.8
